### ISSUE TITLE
Notification Not Received When App Closed

### ISSUE THREAD

**Issue by MattGould1** [dpa99c/cordova-plugin-firebasex-test#5] opened 2019-11-01 13:08 UTC
Hello,

On Android 8.1.0 I am not receiving notifications when the app is closed.

I believe all other notification states are working correctly. When the app is in the background, I receive notifications which are sent to the system tray. When the app is in the foreground, the notification is delivered to the app to handle and not the system tray.

While figuring out what was going on, I came across `autostart`. When the app has `autostart` enabled I can then receive notifications when the app is closed.

I was wondering if there was a  way to prompt/auto enable `autostart` and whether that could be part of this plugin?

Thanks

**Comment by punixxher** [comment] 2019-11-22 16:25
have you some solution from this problem?. i have same inssues
Duplicate of #5

**Comment by dpa99c** [comment] 2019-11-23 09:54
Since there are no device details given, I will assume this is due to the OEM-specific issue outline in [#235](https://github.com/dpa99c/cordova-plugin-firebasex/issues/235)

**Closed as completed by dpa99c** 2019-11-23 09:54 UTC
